### ISSUE TITLE
CLI returns error for artisan commands

### ISSUE THREAD

**Issue by CydeSwype** [JN-Jones/web-artisan#1]
very cool idea and i really need a package like this.  found that the help and clear commands work fine but the password and artisan commands always return an error for me.

artisan@laravel:/$ password
Something went wrong. Probably you entered an invalid command? If it's an error with the package, please let me know.

artisan@laravel:/$ artisan list
Something went wrong. Probably you entered an invalid command? If it's an error with the package, please let me know.
artisan@laravel:/$ artisan
Something went wrong. Probably you entered an invalid command? If it's an error with the package, please let me know.

let me know if i can provide further info to help debug.

**Comment by JN-Jones** [comment]
Could you please test "artisan help" or "password test"? In addition whats your base_url setting?

**Comment by CydeSwype** [comment]
alas, no love:

artisan@laravel:/$ artisan help
Something went wrong. Probably you entered an invalid command? If it's an
error with the package, please let me know.
artisan@laravel:/$ password test
Something went wrong. Probably you entered an invalid command? If it's an
error with the package, please let me know.

base_url is the default.  here's my full config:

return array(
        'enable' => true,
        'base_url' => 'web-artisan',
        'password' => 'test',
        'ips' => array('127.0.0.1', '::1'),
        'auth_filter' => '',
);

-Ian

**Comment by CydeSwype** [comment]
Also, don't know if you know about this project or not already:

https://github.com/joecwallace/web-artisan

I just forked it here and added a little bit of interactivity:

https://github.com/CydeSwype/web-artisan

I think his Joe's project has a lot of the same goals of providing a web
frontend to artisan.  I'm very interested in helping come up with a
solution for this.

-Ian

**Comment by JN-Jones** [comment]
I added a few debug information with my last commit, can you download it and try it again? I'll try to find the issue but for me it's working

**Comment by CydeSwype** [comment]
I see that the debug flag is on in the source but I'm not seeing any new
information coming back.  Where am I supposed to look for the debug
info/messages?

I did think to pop open the chrome developer console and see what
js/network errors were happening though.  It looks like it's 404ing on the
two requests that are failing.  I realize after browsing through the source
a bit more that those are the only two "real" requests.  When hitting those
URLs directly I get:

Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException

And in the access logs, I see it's trying to hit [docroot]/webartisan
(where docroot is my actual document root).  I realized (a bit late) that I
need to change the base url as it's not relative to my current URL but
rather to the document root.  I'm loading the terminal fine from here:

http://127.0.0.1/fglaravel/web-artisan

So I thought having the config set base url to web-artisan was good enough
(since this was loading).  Just changed the config to 'base_url' =>
'/fglaravel/web-artisan' and went back to reload the page and got a:

Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException

Then I went to:

http://127.0.0.1/fglaravel/fglaravel/web-artisan

And it loaded fine... but of course it was making requests to

http://127.0.0.1/fglaravel/web-artisan

So it appears there may be something wrong with the base_url reference?

Let me know if you'd like more information for debugging.

-Ian

**Comment by JN-Jones** [comment]
Ok that could be the issue, I've tested it just at the domain rout (http://laravel.dev/web-artisan and http://laravel.dev/admin/web-artisan). Will test it tomorrow ;)

**Comment by CydeSwype** [comment]
Okay I think I've figured this out.  This line in your blade file:

base_url = '{{ Request::getSchemeAndHttpHost() }}/{{
trim(Config::get('web-artisan::base_url'), "\/") }}/';

Doesn't always handle the base path correctly (for the reason I mentioned
before). Suggest you change this line to this instead:

base_url = '{{ Request::getSchemeAndHttpHost() }}{{
Request::server("REQUEST_URI") }}/';

Which is a bit more foolproof.  This solved the issue for me.

-Ian
