### ISSUE TITLE
Cannot install Stable version with latest Laravel

### ISSUE THREAD

**Issue by piotr-cz** [JN-Jones/web-artisan#11]
Latest stable version (1.0.1) has a requirement of `Illuminate/Support: 4.0.x.`
This has been fixed in commit [#86f93504c8](https://github.com/JN-Jones/web-artisan/commit/86f93504c88438ab702739f0c7347c6034f1f302) on master branch.

Solution: Please tag new Release with this commit, or with require `4.*` or `~4.*`.
I prefer not to use development branches in a project.

**Comment by JN-Jones** [comment]
There weren't any recent changes and due the lack of time there won't be any change soon so you can require the dev version.

**Comment by JN-Jones** [comment]
I've tagged 1.0.2 for now.
