### ISSUE TITLE
Controller:make Does not Work

### ISSUE THREAD

**Issue by Ardakilic** [JN-Jones/web-artisan#3]
Hi,

I'm trying to make a new controller by the artisan command.

I've tried this,

`artisan@laravel:/$ artisan controller:make testController
Controller created successfully!`

But there is no controller appeared.

I'm using a Wampserver on Win8, and shell command creates the file successfully.

Any ideas?

Thanks,

**Comment by JN-Jones** [comment]
I'm not at home for the next few days, but I'll test it afterwards.

**Comment by JN-Jones** [comment]
It seems like it's an Issue with Laravel as the following code doesn't work in any place

``` php
Artisan::call("controller:make", array("testC"));
```

**Comment by JN-Jones** [comment]
Ok I have a solution: the name of the controller needs to be an argument so you should call `artisan controller:make name=testController`. It worked for me so hopefully it does for you too

**Comment by Ardakilic** [comment]
Thanks, that way works flawlessly! Just tried on Linux LAMP (my workspace).

One more tiny issue remains though (not related to this question). It's quite minor so I won't be opening a new question: In Chromium "Version 28.0.1500.71 Ubuntu 13.04 (28.0.1500.71-0ubuntu1.13.04.1)" , space bar doesn't work on webUI. But in FF it works.

Thanks again!

**Comment by JN-Jones** [comment]
I'll look into it when I have time for it

**Comment by JN-Jones** [comment]
I fixed the initial issue
